apiVersion: rbac.authorization.k8s.io/v1
kind: "Role"
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    app: {{ default .Chart.Name }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

