{{- if or .Values.registration.token .Values.authentification.token -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner.secret" . }}
  namespace: {{ default .Release.Namespace | quote }}
  labels:
    app: {{ default .Chart.Name }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  runner-registration-token: {{ default "" .Values.registration.token | b64enc | quote }}
  runner-token: {{ default "" .Values.authentification.token | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner.secret.certs" . }}
  namespace: {{ default .Release.Namespace | quote }}
  labels:
    app: {{ default .Chart.Name }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  certificate: {{ default "" .Values.certs.certificate | b64enc }}
{{ end }}

{{ if .Values.cache.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner.secret.cache" . }}
  namespace: {{ default .Release.Namespace | quote }}
  labels:
    app: {{ default .Chart.Name }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  accesskey: {{ .Values.cache.accessKey | b64enc | quote }}
  secretkey: {{ .Values.cache.secretKey | b64enc | quote }}
{{ end }}